blog/urls.py
from django.conf.urls import include, url
from . import views
from django.contrib.auth import views as auth_views
# from django.contrib.auth.views import login,logout

app_name = "blog"

urlpatterns = [
    url(r'^$', views.post_list, name='post_list'),
    url(r'^kensaku$', views.kensaku, name='kensaku'),
    url(r'^summury$', views.post_list, name='summary'),
    url(r'^add$', views.edit, name='add'),  # 登録
    url(r'^edit/(?P<sales_id>\d+)/$', views.edit, name='edit'),  # 修正
    url(r'^del/(?P<sales_id>\d+)/$', views.sales_del, name='sales_del'),   # 削除
    url(r'^redilect/$', views.post_list, name='redilect'),
    url(
        r'^login/$',
        auth_views.login,
        {'template_name': 'blog/login.html'},
        name='login'
    ),
    url(
        r'^logout/$',
        auth_views.logout,
        {'template_name': 'blog/login.html'},
        name='logout'
    ),
    
]

free/urls.py
from django.contrib import admin
# from django.urls import path
from django.conf.urls import include, url

urlpatterns = [
    url('admin/', admin.site.urls),
    url('', include('blog.urls',namespace='blog')),
    
]

blog/models.py
from django.db import models
from django.utils import timezone
# Create your models here.
class SalseMans(models.Model):
    "担当者"
    man_id = models.IntegerField(primary_key=True)
    name   = models.CharField(max_length=20, unique=True)
    # man_id = models.IntegerField()
    # name   = models.CharField(max_length=20)
    
    def __str__(self):
        return str(self.man_id) + ':' + str(self.name)

class Salse(models.Model):
    sale_man     = models.ForeignKey(SalseMans, on_delete=models.CASCADE,verbose_name="担当者")
    sales_date   = models.DateField(default=timezone.now,verbose_name="売上日")
    sales_mount  = models.IntegerField(verbose_name="金額")
    created_date = models.DateTimeField(default=timezone.now)

blog/forms.py
from django.forms import ModelForm
from blog.models import Salse,SalseMans
from django import forms
import datetime


class SalsesForm(ModelForm):
    "売り上げのフォーム" 
    class Meta:
        model = Salse
        fields = ('sale_man','sales_date','sales_mount',)
        

def Today():
    return datetime.date.today()

def Beginning_of_month():
    Today = datetime.date.today()
    return datetime.date(Today.year, Today.month, 1)
    
class hizuke1Form(forms.Form):
    hizuke1 = forms.DateField(initial=Beginning_of_month, widget=forms.DateInput(attrs={'class':'form-control'}))
    hizuke2 = forms.DateField(initial=Today, widget=forms.DateInput(attrs={'class':'form-control'}))


    

blog/views.py
from django.shortcuts import render, get_object_or_404, redirect, render_to_response
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from blog.models import Salse,SalseMans
from blog.forms import SalsesForm, hizuke1Form
import datetime
import json
from django.db.models import Q
from django.contrib.auth.context_processors import auth
from django.template import RequestContext
from django.contrib.auth.decorators import permission_required
from django.db import transaction


@login_required
def post_list(request):

    if hasattr(request, 'user'):
        user = request.user
    else:
        from django.contrib.auth.models import AnonymousUser
        user = AnonymousUser()

    to_date = datetime.date.today()
    from_date = datetime.date(to_date.year, to_date.month, 1)
    id = [i.name for i in SalseMans.objects.raw('SELECT * FROM blog_SalseMans')]
    name = [i.man_id for i in SalseMans.objects.raw('SELECT * FROM blog_SalseMans')]
    
    List = []
    for i in zip(name, id):
        ID   = i[0]
        name = i[1]
        data = Salse.objects.filter(Q(sales_date__range=[from_date, to_date]),Q(sale_man=ID))
        data = sum([i.sales_mount for i in data])
        y    = {"y":data,"label":name}            
        List.append(y) 
    
    # sales = Salse.objects.all().order_by('id')
    sales = Salse.objects.filter(sales_date__range=[from_date, to_date]).order_by('sales_date').reverse()
    form1 = hizuke1Form()

    return render(request,
                'blog/summary.html',     # 使用するテンプレート
                {'sales': sales,'form1':form1,'data':List,'test':List,'from_date':from_date,'to_date':to_date})         # テンプレートに渡すデータ

@login_required
def kensaku(request):
    
    if request.method == 'POST':
        from_date = request.POST['hizuke1']
        to_date   = request.POST['hizuke2']
        id        = [i.name for i in SalseMans.objects.raw('SELECT * FROM blog_SalseMans')]
        name      = [i.man_id for i in SalseMans.objects.raw('SELECT * FROM blog_SalseMans')]
            
        List = []
        for i in zip(name, id):
            ID   = i[0]
            name = i[1]
            data = Salse.objects.filter(Q(sales_date__range=[from_date, to_date]),Q(sale_man=ID))
            data = sum([i.sales_mount for i in data])  
            y    = {"y":data,"label":name}    
            List.append(y) 
    
        sales = Salse.objects.filter(sales_date__range=[from_date, to_date]).order_by('sales_date').reverse()
        form1 = hizuke1Form()


        from_date = datetime.datetime.strptime(from_date, '%Y-%m-%d')
        to_date   = datetime.datetime.strptime(to_date, '%Y-%m-%d')

        return render(request,
                'blog/summary.html',     # 使用するテンプレート
                {'sales': sales,'form1':form1,'data':List, 'from_date':from_date, 'to_date':to_date})
        
    else:

        to_date   = datetime.date.today()
        from_date = datetime.date(to_date.year, to_date.month, 1)

        id   = [i.name for i in SalseMans.objects.raw('SELECT * FROM blog_SalseMans')]
        name = [i.man_id for i in SalseMans.objects.raw('SELECT * FROM blog_SalseMans')]
        
        List = []
        for i in zip(name, id):
            ID   = i[0]
            name = i[1]

            data = Salse.objects.filter(Q(sales_date__range=[from_date, to_date]),Q(sale_man=ID))
            data = sum([i.sales_mount for i in data])    
            y = {"y":data,"label":name}                
            List.append(y) 

        sales = Salse.objects.filter(sales_date__range=[from_date, to_date]).order_by('sales_date').reverse()
        form1 = hizuke1Form()
        

        return render(request,
                    'blog/summary.html',     # 使用するテンプレート
                    {'sales': sales,'form1':form1,'data':List, 'from_date':from_date, 'to_date':to_date})    # テンプレートに渡すデータ




# @permission_required('blog.can_delete', login_url='/login/')
def edit(request,sales_id=None):

    if sales_id:   # sales_id が指定されている (修正時)
        if not request.user.has_perm('blog.can_delete'):
            return redirect('blog:summary')
        else:
            salse = get_object_or_404(Salse, pk=sales_id)
    else:         # sales_id が指定されていない (追加時)
        salse = Salse()

    if request.method == 'POST':
        form = SalsesForm(request.POST, instance=salse)  # POST された request データからフォームを作成
        if form.is_valid():    # フォームのバリデーション
            salse = form.save(commit=False)
            try:
                salse.save()
                return redirect('blog:summary')
            except IntegrityError:
                transaction.rollback()
    else:    # GET の時
        form = SalsesForm(instance=salse)  # salse インスタンスからフォームを作成

    return render(request, 'blog/edit.html', dict(form=form, sales_id=sales_id))



@login_required
def sales_del(request, sales_id):
    """売り上げの削除"""
    sales = get_object_or_404(Salse, pk=sales_id)
    sales.delete()
    return redirect('blog:summary')



@login_required
def redilect(request):
    return render(request, 'blog/summary.html')

templates/base.html
{% load staticfiles %}
{% load humanize %}
<!DOCTYPE html>
<html lang="{{ LANGUAGE_CODE|default:"en-us" }}">
<head>
<meta charset="UTF-8">
<title>{% block title %}売り上げ{% endblock %}</title>
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.3/css/bootstrap.min.css" integrity="sha384-Zug+QiDoJOrZ5t4lssLdxGhVrurbmBWopoEl+M6BdEfwnCJZtKxi1KgxUyJq13dy" crossorigin="anonymous">
<link rel="shortcut icon" href="{{STATIC_URL}}/favicon.ico">
{% block extrahead %}{% endblock %}
</head>
<body>
  <div class="container">
    {% block content %}
      {{ content }}
    {% endblock %}
  </div>
</body>

</html>

templates/blog/edit.html
{% extends "base.html" %} 
{% load bootstrap %} 
{% block title %}売り上げ編集{% endblock title %} 
{% block extrahead %}
<!-- jQuery first, then Tether, then Bootstrap JS. -->
<script>
  $('[data-toggle=datepicker]').each(function () {
    var target = $(this).data('target-name');
    var t = $('input[name=' + target + ']');
    t.datepicker({
      dateFormat: 'yy-mm-dd',
    });
    $(this).on("click", function () {
      t.datepicker("show");
    });
  });
</script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.0.0/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/tether/1.2.0/js/tether.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/js/bootstrap.min.js"></script>

<!-- カレンダー -->
<script src="http://ajax.googleapis.com/ajax/libs/jqueryui/1/jquery-ui.min.js"></script>
<script src="http://ajax.googleapis.com/ajax/libs/jqueryui/1/i18n/jquery.ui.datepicker-ja.min.js"></script>
<link rel="stylesheet" href="http://ajax.googleapis.com/ajax/libs/jqueryui/1/themes/ui-lightness/jquery-ui.css">
<script>
  $(function () {
    var dateFormat = 'yy-mm-dd';
    $('#id_sales_date').datepicker({
      dateFormat: dateFormat
    });

  });
</script> {% endblock %}
 {% block content %}

{% if sales_id %}
<h3 class="page-header" style="margin-top: 10%;">売上編集</h3>
<form action="{% url 'blog:edit' sales_id=sales_id %}" method="post" class="form-horizontal" role="form">
 
{% else %}
<h3 class="page-header" style="margin-top: 10%;">売上登録</h3>
<form action="{% url 'blog:add' %}" method="post" class="form-horizontal" role="form">

 {% endif %} 
{% csrf_token %}
{{ form|bootstrap_horizontal }}
  
    <br>
    <div class="form-group">
      <div class="col-sm-offset-2 col-sm-10">
        {% if sales_id %}
        <button type="submit" class="btn btn-primary">修正</button>
        {% else %}
        <button type="submit" class="btn btn-primary">登録</button>
        {% endif %} 

        <a href="{% url 'blog:summary' %}" class="btn btn-default btn-sm">戻る</a>
      </div>
    </div>

  </form>


  {% endblock content %} {% block nav %}

  {% endblock %}

templates/blog/login.html
{% extends 'base.html' %} 
{% block content %} 


<div class='container'>
  <center>
<form method='post' action='{% url 'blog:login' %}'>
{% csrf_token %}
<br><br><br><br><br><br><br>
    <div class="form-horizontal">{{ form.username.label_tag }}</div>
    <br>
    <div class="form-horizontal">{{ form.username }}</div>
    <br>
    <div class="form-horizontal">{{ form.password.label_tag }}</div>
    <br>
    <div class="form-horizontal">{{ form.password }}</div>
    <br>
 
<input class="btn btn-outline-primary" type='submit' value='Login' />
<input class="btn btn-outline-primary" type='hidden' name='next' value='{{ next }}' />
</form>
</div>
</center>
{% endblock %}

templates/blog/summary.html
{% extends "base.html" %}{% load bootstrap %}

{% block title %}売り上げ集計{% endblock title %}


<!DOCTYPE html>
{% block extrahead %}
<script src="https://canvasjs.com/assets/script/canvasjs.min.js"></script>
<script>
window.onload = function () {

var chart = new CanvasJS.Chart("chartContainer", {
	animationEnabled: true,
	title:{
		text: ""
	},
	axisX: {
		valueFormatString: "DDD"
	},
	axisY: {
		prefix: "￥"
	},
	toolTip: {
		shared: true
	},
	legend:{
		cursor: "pointer",
		itemclick: toggleDataSeries
	},
	data: [
	{
		type: "stackedBar",
		name: "売上",
		yValueFormatString: "￥###,###,###",
		dataPoints: {{ data|safe }}
    // [
		// 	{ x: new Date(2017, 0, 30), y: 52 },
		// 	{ x: new Date(2017, 0, 31), y: 55 },
		// 	{ x: new Date(2017, 1, 1), y: 20 },
		// 	{ x: new Date(2017, 1, 2), y: 35 },
		// 	{ x: new Date(2017, 1, 3), y: 30 },
		// 	{ x: new Date(2017, 1, 4), y: 45 },
		// 	{ x: new Date(2017, 1, 5), y: 25 }
		// ]
	}]
});
chart.render();

function toggleDataSeries(e) {
	if(typeof(e.dataSeries.visible) === "undefined" || e.dataSeries.visible) {
		e.dataSeries.visible = false;
	}
	else {
		e.dataSeries.visible = true;
	}
	chart.render();
}

}
</script>

<!-- jQuery first, then Tether, then Bootstrap JS. -->
<script>
  $('[data-toggle=datepicker]').each(function () {
    var target = $(this).data('target-name');
    var t = $('input[name=' + target + ']');
    t.datepicker({
      dateFormat: 'yy-mm-dd',
    });
    $(this).on("click", function () {
      t.datepicker("show");
    });
  });
</script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.0.0/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/tether/1.2.0/js/tether.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/js/bootstrap.min.js"></script>

<!-- カレンダー -->
<script src="http://ajax.googleapis.com/ajax/libs/jqueryui/1/jquery-ui.min.js"></script>
<script src="http://ajax.googleapis.com/ajax/libs/jqueryui/1/i18n/jquery.ui.datepicker-ja.min.js"></script>
<link rel="stylesheet" href="http://ajax.googleapis.com/ajax/libs/jqueryui/1/themes/ui-lightness/jquery-ui.css">
<script>
  $(function () {
    var dateFormat = 'yy-mm-dd';
    $('#id_hizuke1').datepicker({
      dateFormat: dateFormat
    });

  });
</script>

<!-- jQuery first, then Tether, then Bootstrap JS. -->
<script>
  $('[data-toggle=datepicker]').each(function () {
    var target = $(this).data('target-name');
    var t = $('input[name=' + target + ']');
    t.datepicker({
      dateFormat: 'yy-mm-dd',
    });
    $(this).on("click", function () {
      t.datepicker("show");
    });
  });
</script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.0.0/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/tether/1.2.0/js/tether.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/js/bootstrap.min.js"></script>

<!-- カレンダー -->
<script src="http://ajax.googleapis.com/ajax/libs/jqueryui/1/jquery-ui.min.js"></script>
<script src="http://ajax.googleapis.com/ajax/libs/jqueryui/1/i18n/jquery.ui.datepicker-ja.min.js"></script>
<link rel="stylesheet" href="http://ajax.googleapis.com/ajax/libs/jqueryui/1/themes/ui-lightness/jquery-ui.css">
<script>
  $(function () {
    var dateFormat = 'yy-mm-dd';
    $('#id_hizuke2').datepicker({
      dateFormat: dateFormat
    });

  });
</script>


<link rel="stylesheet" type="text/css" href="summary.css">

{% endblock %}

{% block content %}


<br>

  <div class="container">

      <center><h5>売り上げ集計</h5></center>

      <center> {{from_date|date:"Y-m-d"}}&nbsp;~&nbsp;{{to_date|date:"Y-m-d"}}</center>


    <div id="chartContainer" style="height: 370px; width: 100%;"></div>
    <script src="https://canvasjs.com/assets/script/canvasjs.min.js"></script>
    <center>
      <br>

      <form action="{% url 'blog:kensaku' %}" method="post" role="form">
        {% csrf_token %}
        From{{ form1.hizuke1}}
        
        To:{{ form1.hizuke2}}
        <br>
        <a href="{% url 'blog:kensaku' %}"><button name='period' type="submit" class="btn btn-outline-primary">検索開始</button></a>
        
      </form>
      
      <hr>

      <a href="{% url 'blog:add' %}"><button type="button" class="btn btn-outline-primary">売り上げ入力</button></a>
      
      <br><br>
    </center>

    <table class="table table-striped table-bordered">
      <thead>
        <tr style="text-align: center;">
          <th>担当者</th>
          <th>金額</th>
          <th>売上日</th>  
          <!-- <th>作成日</th> -->
          {% if perms.blog %}
            {% if perms.blog.can_delete %}
          <th>操作</th>
            {% endif %}
            {% else %}
            {% endif %}
        </tr>
      </thead>
      <tbody>
          
        {% for sale in sales %}
        {% load humanize %}
        <tr>
          <td style="text-align: center;">{{ sale.sale_man }}</td>
          <td style="text-align: right;" >￥{{ sale.sales_mount| intcomma}}-</td>
          <td style="text-align: right;">{{ sale.sales_date|date:"Y-m-d" }}</td>
          <!-- <td>{{ sale.created_date }}</td> -->
          {% if perms.blog %}
            {% if perms.blog.can_delete %}
          <td style="text-align: center;">
            <a href="{% url 'blog:edit' sales_id=sale.id %}" class="btn btn-default btn-sm">修正</a> 
            <a href="{% url 'blog:sales_del' sales_id=sale.id %}" class="btn btn-default btn-sm">削除</a>
          </td>
          {% endif %}
          {% else %}
          {% endif %}
        </tr>
        {% endfor %}
      </tbody>
    </table>
 
  </div>

  <br><br><br><br><br>
  
{% endblock content %}



</html>